feat: map idp roles to auth0 roles during authentication
ebot7/auth0-integration pull request #3
Opened 2021-11-28 22:52 UTC by chandhravadanan

2021-11-29 08:26 UTC, nishant-ebot7 reviewed
We should not mix `.then`, `async/await` and `callback` patterns.
Let's use `.then` pattern everywhere since top level async/await is not possible.

We can still keep the functionality seperate in different functions and then one main promise chain to compose all the functions.

2021-11-29 08:39 UTC, ales-albert-kilbergr requested changes

2021-11-29 08:39 UTC, ales-albert-kilbergr commented on rules/setRolesToUser.js
> +  function getAccessToken(cb) {
I would personally preferred to use chain of promises instead of callback approach. If possible with `async/await` syntax sugar. Code would not need probably to declare a `getAccessToken` function at all.

Like:

```js
try {
  const response = await axios.post(...)....
  
  if (!response.data || !response.data.accessToken) {
         throw new Error('some error here');
   }
  const accessToken = response.data.accessToken;
  global.accessToken = accessToken;
  const orgsInfoRes = await axios({
    method: "GET",
    url: `${configuration.AUTH_ENDPOINT}/orgs?auth0OrgId=${context.organization.id}`,
    headers: { Authorization: accessToken },
  });
  const resData = orgsInfoRes.data;
  const orgInfo = resData && resData.data && resData.data[0];

  if (!orgInfo) {
    throw new Error('some error probably with some code')
   }  
  ...
  
  if (!orgInfo.idpConfig || !orgInfo.idpConfig.roleMapping) {
    throw new Error('another error to describe this', context.organisation.id);
  }    
   
} catch (error) {
  // do some general error login
  callback(null, user, context);
}
```

The `callback` approach feels like from early nodejs days before `promise` had been standartized.

2021-11-29 08:39 UTC, ales-albert-kilbergr commented on rules/setRolesToUser.js
> +    axios
I would rather use `async/await` consistently in whole script as you do on line `43`

2021-11-29 10:28 UTC, chandhravadanan commented on rules/setRolesToUser.js
> +    axios
used async/await

2021-11-29 10:28 UTC, chandhravadanan commented on rules/setRolesToUser.js
> +  function getAccessToken(cb) {
used async/await

2021-11-29 10:29 UTC, chandhravadanan commented
> We should not mix `.then`, `async/await` and `callback` patterns. Let's use `.then` pattern everywhere since top level async/await is not possible.
> 
> We can still keep the functionality seperate in different functions and then one main promise chain to compose all the functions.

looks like top level function supports async/await and modified

2021-11-29 13:21 UTC, nishant-ebot7 approved these changes

2021-11-29 13:21 UTC, nishant-ebot7 commented on rules/setRolesToUser.js
> +  }
We can define this out of main function no? 
Lets take out all the helper function out of main function if possible

2021-11-29 13:25 UTC, chandhravadanan commented on rules/setRolesToUser.js
> +  }
function definition outside main function not allowed in auth0 rules.

2021-11-30 08:43 UTC, ales-albert-kilbergr approved these changes
LGTM

2021-11-30 08:48 UTC, merged